# Generated by Django 2.0.1 on 2018-04-29 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0004_auto_20180429_0513'),
        ('core', '0002_auto_20180428_1820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
