# Generated by Django 2.0.1 on 2018-05-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20180503_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalevent',
            name='duration',
            field=models.CharField(default='', max_length=50),
        ),
    ]
