# Generated by Django 2.0.1 on 2018-04-16 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_event_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaneEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Event')),
            ],
            bases=('core.event',),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.IntegerField(default=0)),
                ('is_empty', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeatingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_no', models.IntegerField(default=0)),
                ('col_no', models.IntegerField(default=0)),
                ('plane_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plane.PlaneEvent')),
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='seating_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plane.SeatingPlan'),
        ),
    ]
