# Generated by Django 2.0.1 on 2018-04-28 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0002_auto_20180423_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planeevent',
            name='schedule',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.Schedule'),
        ),
    ]
