# Generated by Django 2.0.1 on 2018-04-17 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0003_auto_20180417_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planeevent',
            name='seating_plan',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='plane.SeatingPlan'),
        ),
    ]
