# Generated by Django 2.0.1 on 2018-04-29 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0003_auto_20180428_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planeevent',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='planeticket',
            name='schedule',
        ),
    ]
