# Generated by Django 2.0.1 on 2018-04-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0004_auto_20180429_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='planeevent',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='planeevent',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
