# Generated by Django 2.0.1 on 2018-04-29 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0006_planeticket_seat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seatingplan',
            old_name='plane_event',
            new_name='event',
        ),
    ]
