# Generated by Django 2.0.1 on 2018-04-29 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0010_auto_20180429_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='is_empty',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='seat_no',
        ),
    ]
