# Generated by Django 2.0.1 on 2018-04-29 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0012_auto_20180429_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planeticket',
            old_name='event',
            new_name='plane_event',
        ),
    ]
